version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:ro
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://localhost:6379/0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data: